### ISSUE TITLE
CSS is not updating

### ISSUE THREAD

**Issue by Pshemas** [TryGhost/Dope#17]
I'm running Ghost using container image.

I'd love to change size of the logo. I've modified /assets/css/site/header.css and changed :
.logo-image {
    max-height: 80px;
}

to:

.logo-image {
    max-height: 80px;
}

- but it does not change anything. I've even tried renaming the the modified theme and reuploading theme but it does not work either. Any ideas what's wrong?

**Comment by minimaluminium** [comment]
Hey @Pshemas, you'll need to install the dependencies and run them to get the CSS compiled. You can read more about it [here](https://github.com/TryGhost/Dope#development) in section "Development".

Also your before/after CSS looks same, so that might be the reason why you're not seeing any change.

If your changes are minor (like this one), you could directly add your changes in "Code injection > Site Header" section in the admin. In this case, you won't need to install any development tools, the CSS will just override the existing one.

**Comment by Pshemas** [comment]
thanks for the code injection tip. 
Yeah, I've copied the wrong part of code in the example above - should have been "max-height: 40px;" in the first example.

I've tried compiling the package but evidently did something wrong and the theme stopped working - there's a lack of easy to follow tutorials on this matter when it comes to Ghost. Also it's a shame we have to go through such hoops just to did a bit of visual tweaks to the site.
