### ISSUE TITLE
homepage view and click behaviour using Ghost Pro (Official Theme Dope - $9/mo)

### ISSUE THREAD

**Issue by crowdsense** [TryGhost/Dope#22]
Hi 

I am trying to understand the following is a bug or?

dope ACTIVE
Version 1.0.0

Ghost pro - after sign-up comes with default content. e.g., 1 tag "Getting Started" and 6 post under that tag. I deleted 5 post and kept 1. Below is the view of my homepage my questions are:

![Screen Shot 2021-10-30 at 11 34 26 am](https://user-images.githubusercontent.com/86043695/139513912-e5fd7665-e6cb-448f-b5ac-54f33dd635ce.png)

- is this the correct layout? maybe the theme needs minimum of two tags so the layout is not half empty. It works well on mobile view. maybe I am missing some configurations? - please advise?
- currently when I click on the tag it goes to tag archive page with 1 post - so the user need to click again to go to the post - is it possible I can take the user directly to the post if a tag has only 1 post attached to it? - any workaround?

Maybe the above only possible if I upgrade to a higher plan - that's ok - but do I also need to know lot about theme design to achieve above click and view behaviour?

Many thanks

**Comment by minimaluminium** [comment]
Hey @crowdsense,

The layout issue was fixed in https://github.com/TryGhost/Dope/commit/21bd87b735033def0295b398d0fae30c3057ab7c. It now calculates the number of tags and shows the correct layout dynamically. 

Re: linking directly to a post, this is out of context from the primary use case of the theme. We're not planning to update the theme for this kind of edge case.
